services:
  db:
    container_name: wildberries_scraper_db
    image: postgres:16
    shm_size: "2gb"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
    networks:
      - app_network

  web:
    container_name: wildberries_scraper_backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 9
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: "2.0"
    volumes:
        - ./static:/home/app/web/static
        - ./staticfiles:/home/app/web/staticfiles
        - ./media:/home/app/web/media
        - ./locale:/home/app/web/locale
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  redis:
    container_name: wildberries_scraper_redis
    image: redis:7.2.4-alpine
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

  celery_worker:
    container_name: wildberries_scraper_celery_worker
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: celery_worker
    command: /start-celeryworker
    volumes:
      - .:/home/app/web/
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web

  celery_beat:
    container_name: wildberries_scraper_celery_beat
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: celery_beat
    command: /start-celerybeat
    volumes:
      - .:/home/app/web/
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

networks:
    app_network:

volumes:
  postgres_data:
  static_volume:
  media_volume:
