#!/bin/bash

# To update run
pip install --upgrade pip

# Install required packages (change this if needed)
pip install -r requirements.txt

watchfiles \
  --filter python \
  'celery -A config worker --loglevel=info'
