#!/bin/bash

source /root/wildberries_scraper/venv/bin/activate

# To update run
pip install --upgrade pip

# Install required packages (change this if needed)
pip install -r requirements.txt

watchfiles \
  --filter python \
  'celery -A config worker --loglevel=info'
