# Generated by Django 5.1 on 2024-08-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userotp",
            name="type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("forgot_password", "Forgot password"),
                ],
                default="register",
                max_length=20,
            ),
        ),
    ]
