# Generated by Django 5.1 on 2024-08-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users_users",
        ),
    ]
