#!/bin/bash

source /root/wildberries_scraper/venv/bin/activate

# To update run
pip install --upgrade pip

# Install required packages (change this if needed)
pip install -r requirements.txt

rm -f './celerybeat.pid'
celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
