# Generated by Django 5.0.7 on 2024-08-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_remove_duplicates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentfiles",
            name="file_link",
            field=models.TextField(default=1, unique=True, verbose_name="File link"),
            preserve_default=False,
        ),
    ]
