# Generated by Django 5.0.7 on 2024-08-19 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="commentfiles",
            options={
                "verbose_name": "Comment file",
                "verbose_name_plural": "Comment files",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Favorite", "verbose_name_plural": "Favorites"},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Like", "verbose_name_plural": "Likes"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "verbose_name": "Product variant",
                "verbose_name_plural": "Product variants",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariantimage",
            options={
                "verbose_name": "Product variant image",
                "verbose_name_plural": "Product variant images",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="image_link",
            field=models.TextField(blank=True, null=True, verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="scraper.category",
                verbose_name="Parent category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="shard",
            field=models.TextField(blank=True, null=True, verbose_name="Shard"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_name",
            field=models.TextField(blank=True, null=True, verbose_name="Slug name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="source_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Source ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="comments/files/", verbose_name="File"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_comments",
                to="scraper.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="scraper.comment",
                verbose_name="Reply to",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="source_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Source ID"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("not_accepted", "Not accepted"),
                    ("not_reviewed", "Not reviewed"),
                ],
                default="not_reviewed",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="wb_user",
            field=models.TextField(
                blank=True, null=True, verbose_name="Wildberries user"
            ),
        ),
        migrations.AlterField(
            model_name="commentfiles",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="scraper.comment",
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="commentfiles",
            name="file_link",
            field=models.TextField(blank=True, null=True, verbose_name="File link"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_favorites",
                to="scraper.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_likes",
                to="scraper.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="scraper.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="root",
            field=models.IntegerField(blank=True, null=True, verbose_name="Root"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.TextField(blank=True, null=True, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.TextField(blank=True, null=True, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="scraper.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="source_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Source ID"
            ),
        ),
        migrations.AlterField(
            model_name="productvariantimage",
            name="image_link",
            field=models.TextField(blank=True, null=True, verbose_name="Image link"),
        ),
        migrations.AlterField(
            model_name="productvariantimage",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="scraper.productvariant",
                verbose_name="Product variant",
            ),
        ),
    ]
