# Generated by Django 5.0.7 on 2024-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_alter_commentfiles_file_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
