# Generated by Django 5.0.7 on 2024-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_alter_category_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantimage",
            name="image_link",
            field=models.TextField(unique=True, verbose_name="Image link"),
        ),
    ]
