# Generated by Django 5.0.7 on 2024-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_category_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="promo",
            field=models.BooleanField(default=False),
        ),
    ]
