# Generated by Django 5.0.8 on 2024-09-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_comment_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="product_source_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="promo",
            field=models.BooleanField(default=False, verbose_name="Promo"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="scraper.category",
                verbose_name="Category",
            ),
        ),
    ]
