# Generated by Django 5.0.7 on 2024-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_productvariantimage_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="source_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
