# Generated by Django 5.0.7 on 2024-08-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0006_comment_source_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestedComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="scraper.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requested comment",
                "verbose_name_plural": "Requested comments",
            },
            bases=("scraper.comment",),
        ),
        migrations.CreateModel(
            name="RequestedCommentFile",
            fields=[
                (
                    "commentfiles_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="scraper.commentfiles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requested comment file",
                "verbose_name_plural": "Requested comment files",
            },
            bases=("scraper.commentfiles",),
        ),
    ]
