# Generated by Django 5.0.7 on 2024-08-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0007_requestedcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedcommentfile",
            name="requested_comment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_files",
                to="scraper.requestedcomment",
                verbose_name="Comment",
            ),
            preserve_default=False,
        ),
    ]
