# Generated by Django 5.0.8 on 2024-09-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0007_category_category_title_upper_index_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productvariantimage",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_link",
        ),
        migrations.AddField(
            model_name="product",
            name="source_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Source ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id", None), _negated=True),
                fields=("source_id",),
                name="unique_source_id_exclude_null_product",
            ),
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
        migrations.DeleteModel(
            name="ProductVariantImage",
        ),
    ]
