# Generated by Django 5.0.8 on 2024-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0008_remove_productvariant_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
