# Generated by Django 5.0.8 on 2024-10-04 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0008_remove_productvariant_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="category_title_upper_index",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_title_upper_index",
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["status"], name="status_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["file_type"], name="file_type_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["source_date"], name="source_date_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["product"], name="product_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["promo"], name="promo_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["status", "content"], name="status_content_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["product", "source_id"], name="product_source_id_idx"
            ),
        ),
    ]
