# Generated by Django 5.0.8 on 2024-10-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0011_set_image_link_from_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedcomment",
            name="comment_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
